/*
 * Copyright (c) 2019 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#ifndef _MOTION_SENSOR_H_
#define _MOTION_SENSOR_H_
#include <zephyr/kernel.h>

#include <zephyr/types.h>

// Define a callback for fast data egress (dx, dy)
typedef void (*motion_fast_path_cb_t)(int16_t dx, int16_t dy);

/**
 * @brief Register a callback for high-performance polling.
 * If registered, the sensor will call this instead of submitting standard events
 * when in "Fast/ESB" mode.
 */
void motion_sensor_set_fast_path_cb(motion_fast_path_cb_t cb);
typedef void (*motion_fast_path_flush_cb_t)(void);
void motion_sensor_set_fast_path_flush_cb(motion_fast_path_flush_cb_t cb);

enum motion_sensor_option {
	MOTION_SENSOR_OPTION_CPI,
	MOTION_SENSOR_OPTION_SLEEP_ENABLE,
	MOTION_SENSOR_OPTION_SLEEP1_TIMEOUT,
	MOTION_SENSOR_OPTION_SLEEP2_TIMEOUT,
	MOTION_SENSOR_OPTION_SLEEP3_TIMEOUT,
	MOTION_SENSOR_OPTION_SLEEP1_SAMPLE_TIME,
	MOTION_SENSOR_OPTION_SLEEP2_SAMPLE_TIME,
	MOTION_SENSOR_OPTION_SLEEP3_SAMPLE_TIME,
	/* New Configuration Parameters */
	MOTION_SENSOR_OPTION_CPI_STAGE_1,
	MOTION_SENSOR_OPTION_CPI_STAGE_2,
	MOTION_SENSOR_OPTION_CPI_STAGE_3,
	MOTION_SENSOR_OPTION_CPI_STAGE_4,
	MOTION_SENSOR_OPTION_CPI_STAGE_ACTIVE,
	MOTION_SENSOR_OPTION_POLLING_RATE_ESB,
	MOTION_SENSOR_OPTION_POLLING_RATE_USB,
	MOTION_SENSOR_OPTION_RIPPLE_CONTROL,
	MOTION_SENSOR_OPTION_ANGLE_SNAP,
	MOTION_SENSOR_OPTION_LOD,

	MOTION_SENSOR_OPTION_COUNT,
};

#if CONFIG_DESKTOP_MOTION_SENSOR_PMW3360_ENABLE

#include <sensor/pmw3360.h>

#define MOTION_SENSOR_COMPATIBLE pixart_pmw3360

static const int motion_sensor_option_attr[MOTION_SENSOR_OPTION_COUNT] = {
	[MOTION_SENSOR_OPTION_CPI] = PMW3360_ATTR_CPI,
	[MOTION_SENSOR_OPTION_SLEEP_ENABLE] = PMW3360_ATTR_REST_ENABLE,
	[MOTION_SENSOR_OPTION_SLEEP1_TIMEOUT] = PMW3360_ATTR_RUN_DOWNSHIFT_TIME,
	[MOTION_SENSOR_OPTION_SLEEP2_TIMEOUT] = PMW3360_ATTR_REST1_DOWNSHIFT_TIME,
	[MOTION_SENSOR_OPTION_SLEEP3_TIMEOUT] = PMW3360_ATTR_REST2_DOWNSHIFT_TIME,
	[MOTION_SENSOR_OPTION_SLEEP1_SAMPLE_TIME] = PMW3360_ATTR_REST1_SAMPLE_TIME,
	[MOTION_SENSOR_OPTION_SLEEP2_SAMPLE_TIME] = PMW3360_ATTR_REST2_SAMPLE_TIME,
	[MOTION_SENSOR_OPTION_SLEEP3_SAMPLE_TIME] = PMW3360_ATTR_REST3_SAMPLE_TIME,
};

#elif CONFIG_DESKTOP_MOTION_SENSOR_PAW3212_ENABLE

#include <sensor/paw3212.h>

#define MOTION_SENSOR_COMPATIBLE pixart_paw3212

static const int motion_sensor_option_attr[MOTION_SENSOR_OPTION_COUNT] = {
	[MOTION_SENSOR_OPTION_CPI] = PAW3212_ATTR_CPI,
	[MOTION_SENSOR_OPTION_SLEEP_ENABLE] = PAW3212_ATTR_SLEEP_ENABLE,
	[MOTION_SENSOR_OPTION_SLEEP1_TIMEOUT] = PAW3212_ATTR_SLEEP1_TIMEOUT,
	[MOTION_SENSOR_OPTION_SLEEP2_TIMEOUT] = PAW3212_ATTR_SLEEP2_TIMEOUT,
	[MOTION_SENSOR_OPTION_SLEEP3_TIMEOUT] = PAW3212_ATTR_SLEEP3_TIMEOUT,
	[MOTION_SENSOR_OPTION_SLEEP1_SAMPLE_TIME] = PAW3212_ATTR_SLEEP1_SAMPLE_TIME,
	[MOTION_SENSOR_OPTION_SLEEP2_SAMPLE_TIME] = PAW3212_ATTR_SLEEP2_SAMPLE_TIME,
	[MOTION_SENSOR_OPTION_SLEEP3_SAMPLE_TIME] = PAW3212_ATTR_SLEEP3_SAMPLE_TIME,
};

#elif CONFIG_DESKTOP_MOTION_SENSOR_PAW3395_ENABLE

#include <sensor/paw3395.h>

#define MOTION_SENSOR_COMPATIBLE pixart_paw3395

static const int motion_sensor_option_attr[MOTION_SENSOR_OPTION_COUNT] = {
	[MOTION_SENSOR_OPTION_CPI] = PAW3395_ATTR_CPI,
	[MOTION_SENSOR_OPTION_SLEEP_ENABLE] = PAW3395_ATTR_REST_ENABLE,
	[MOTION_SENSOR_OPTION_SLEEP1_TIMEOUT] = PAW3395_ATTR_RUN_DOWNSHIFT_TIME,
	[MOTION_SENSOR_OPTION_SLEEP2_TIMEOUT] = PAW3395_ATTR_REST1_DOWNSHIFT_TIME,
	[MOTION_SENSOR_OPTION_SLEEP3_TIMEOUT] = PAW3395_ATTR_REST2_DOWNSHIFT_TIME,
	[MOTION_SENSOR_OPTION_SLEEP1_SAMPLE_TIME] = PAW3395_ATTR_REST1_SAMPLE_TIME,
	[MOTION_SENSOR_OPTION_SLEEP2_SAMPLE_TIME] = PAW3395_ATTR_REST2_SAMPLE_TIME,
	[MOTION_SENSOR_OPTION_SLEEP3_SAMPLE_TIME] = PAW3395_ATTR_REST3_SAMPLE_TIME,

	/* Map new options to sensor attributes so generic loop handles them */
	[MOTION_SENSOR_OPTION_RIPPLE_CONTROL] = PAW3395_ATTR_RIPPLE_CONTROL,
	[MOTION_SENSOR_OPTION_ANGLE_SNAP] = PAW3395_ATTR_ANGLE_SNAP,
	[MOTION_SENSOR_OPTION_LOD] = PAW3395_ATTR_LOD,

	/* These are storage-only or firmware-logic options, not direct sensor attributes */
	[MOTION_SENSOR_OPTION_CPI_STAGE_1] = -ENOTSUP,
	[MOTION_SENSOR_OPTION_CPI_STAGE_2] = -ENOTSUP,
	[MOTION_SENSOR_OPTION_CPI_STAGE_3] = -ENOTSUP,
	[MOTION_SENSOR_OPTION_CPI_STAGE_4] = -ENOTSUP,
	[MOTION_SENSOR_OPTION_CPI_STAGE_ACTIVE] = -ENOTSUP,
	[MOTION_SENSOR_OPTION_POLLING_RATE_ESB] = -ENOTSUP,
	[MOTION_SENSOR_OPTION_POLLING_RATE_USB] = -ENOTSUP,
};

#else

#error "Sensor not supported"

#endif

#endif /* _MOTION_SENSOR_H_ */
