"""Per-release QA checklist generator (HIL-verification REQs only)."""
from __future__ import annotations

from reqtool.trace import Matrix


def build_checklist(matrix: Matrix, tag: str, products: list[str]) -> str:
    relevant = [
        row for row in matrix.rows.values()
        if row.req.verification == "HIL"
        and any(p in row.req.products for p in products)
    ]
    relevant.sort(key=lambda r: r.req.id)

    lines = [
        f"# Release QA: {tag}",
        "",
        f"Auto-generated by `reqtool checklist --tag {tag}`. Tick boxes after manual",
        "verification on physical hardware. Close this issue (with all boxes ticked)",
        "to promote the GitHub Release from draft to published.",
        "",
        "## HIL verification",
        "",
    ]
    if not relevant:
        lines.append("_No HIL-verification requirements apply to this release._")
    else:
        for row in relevant:
            lines.append(f"- [ ] {row.req.id}: {row.req.title}")

    lines += [
        "",
        "## Sign-off",
        "",
        "- [ ] QA lead approval",
        "- [ ] FW lead approval",
        "",
    ]
    return "\n".join(lines) + "\n"
